---
- hosts: all
  vars_files:
    - env_variables
  tasks:
    
    - name: Copy token to worker nodes
      copy: src={{ token_file }} dest=join_token

    - name: Join worker nodes with kubernetes master
      shell: "`grep -i 'kubeadm join' join_token`"

